import logging
from collections import Counter

from torch.utils.data import DataLoader

from base_model_training.io_utils import load_jsonl

LOGGER = logging.getLogger(__name__)


def tokenize_with_spans(text):
    """Split text by whitespace and return (tokens, char spans)."""
    tokens = []
    token_spans = []
    start = 0
    while start < len(text):
        while start < len(text) and text[start].isspace():
            start += 1
        if start >= len(text):
            break
        end = start
        while end < len(text) and not text[end].isspace():
            end += 1
        token = text[start:end]
        tokens.append(token)
        token_spans.append((start, end))
        start = end
    return tokens, token_spans


def process_sample(sample):
    """Map char spans to token spans for a single example."""
    text = sample["text"]
    spans = sample.get("spans", [])
    tokens, token_spans = tokenize_with_spans(text)

    ner = []
    for span in spans:
        start_char = span["start"]
        end_char = span["end"]
        label = span["label"]
        start_token = None
        end_token = None

        for i, (t_start, t_end) in enumerate(token_spans):
            if t_start >= start_char and t_end <= end_char:
                if start_token is None:
                    start_token = i
                end_token = i
            elif t_start < end_char and t_end > start_char:
                if start_token is None:
                    start_token = i
                end_token = i

        if start_token is not None and end_token is not None:
            ner.append([start_token, end_token, label])

    sample_id = sample.get("sample_id")
    return {"tokenized_text": tokens, "ner": ner, "sample_id": sample_id}


def load_dataset(path):
    """Load JSONL and preprocess into tokenized samples."""
    dataset = []
    assigned_sample_ids = 0
    seen_sample_ids = []
    for index, sample in enumerate(load_jsonl(path)):
        enriched = dict(sample)
        if enriched.get("sample_id") is None:
            enriched["sample_id"] = f"sample_{index}"
            assigned_sample_ids += 1
        else:
            seen_sample_ids.append(str(enriched["sample_id"]))
        dataset.append(process_sample(enriched))

    if assigned_sample_ids:
        LOGGER.info(
            "Assigned autogenerated sample_id values to %s input records that did not provide one.",
            assigned_sample_ids,
        )

    duplicate_counts = Counter(seen_sample_ids)
    duplicate_ids = sorted(sample_id for sample_id, count in duplicate_counts.items() if count > 1)
    if duplicate_ids:
        preview = ", ".join(duplicate_ids[:5])
        if len(duplicate_ids) > 5:
            preview += ", ..."
        LOGGER.warning(
            "Found %s duplicated sample_id values in the input dataset. "
            "Nested CV will treat records sharing a sample_id as the same group. "
            "Examples: %s",
            len(duplicate_ids),
            preview,
        )

    return dataset


def _special_tokens_to_add(tokenizer):
    """Return the number of special tokens the encoder inserts per example."""
    if tokenizer is None or not hasattr(tokenizer, "num_special_tokens_to_add"):
        return 0
    try:
        return int(tokenizer.num_special_tokens_to_add(pair=False))
    except TypeError:
        return int(tokenizer.num_special_tokens_to_add())


def _wordpiece_lengths(words, tokenizer):
    """Estimate encoder wordpiece lengths for whitespace-tokenized words."""
    if tokenizer is None:
        return [1] * len(words)

    try:
        encoded = tokenizer(
            words,
            is_split_into_words=True,
            add_special_tokens=False,
            truncation=False,
            return_attention_mask=False,
        )
        word_ids = encoded.word_ids()
        if word_ids is not None:
            lengths = [0] * len(words)
            for word_id in word_ids:
                if word_id is not None:
                    lengths[word_id] += 1
            return [length if length > 0 else 1 for length in lengths]
    except Exception:
        pass

    lengths = []
    for word in words:
        try:
            pieces = tokenizer.tokenize(word)
        except Exception:
            pieces = None
        lengths.append(len(pieces) if pieces else 1)
    return lengths


def _find_chunk_end(wordpiece_lengths, start_idx, budget):
    """Return the exclusive end index of the largest chunk that fits the budget."""
    used = 0
    end_idx = start_idx
    while end_idx < len(wordpiece_lengths):
        next_len = max(1, wordpiece_lengths[end_idx])
        if used and used + next_len > budget:
            break
        if not used and next_len > budget:
            return end_idx + 1
        used += next_len
        end_idx += 1
    return end_idx


def split_long_sentences(dataset, max_length=384, overlap=50, tokenizer=None):
    """Split long tokenized sequences using encoder-aware chunk sizes."""
    split_data = []
    budget = max(1, max_length - _special_tokens_to_add(tokenizer))
    truncated_single_words = 0

    for sample in dataset:
        words = sample.get("tokenized_text", [])
        ner_annotations = sample.get("ner", [])

        if not words or not isinstance(ner_annotations, list):
            continue

        wordpiece_lengths = _wordpiece_lengths(words, tokenizer)
        total_wordpieces = sum(wordpiece_lengths)
        if total_wordpieces > budget:
            start_idx = 0
            while start_idx < len(words):
                end_idx = _find_chunk_end(wordpiece_lengths, start_idx, budget)
                if end_idx <= start_idx:
                    end_idx = start_idx + 1

                current_words = words[start_idx:end_idx]
                if max(wordpiece_lengths[start_idx:end_idx]) > budget:
                    truncated_single_words += 1

                new_ner = []
                for start, end, label in ner_annotations:
                    if max(start, start_idx) <= min(end, end_idx - 1):
                        adjusted_start = max(0, start - start_idx)
                        adjusted_end = min(len(current_words) - 1, end - start_idx)
                        if adjusted_start <= adjusted_end:
                            new_ner.append([adjusted_start, adjusted_end, label])

                split_sample = {
                    "tokenized_text": current_words,
                    "ner": new_ner,
                    "sample_id": sample.get("sample_id"),
                }
                if split_sample["ner"]:
                    split_data.append(split_sample)

                if end_idx >= len(words):
                    break

                next_start_idx = max(start_idx + 1, end_idx - overlap)
                start_idx = next_start_idx
        else:
            if ner_annotations:
                split_data.append(
                    {
                        "tokenized_text": words,
                        "ner": ner_annotations,
                        "sample_id": sample.get("sample_id"),
                    }
                )

    if truncated_single_words:
        LOGGER.warning(
            "%s chunks contain at least one word whose encoder tokenization exceeds the chunk budget of %s. "
            "Those words may still be truncated by GLiNER.",
            truncated_single_words,
            budget,
        )

    return [ex for ex in split_data if "ner" in ex and isinstance(ex["ner"], list) and ex["ner"]]


def create_dataloader(dataset, batch_size, collator, shuffle=True):
    """Build a torch DataLoader with the GLiNER collator."""
    return DataLoader(dataset, batch_size=batch_size, collate_fn=collator, shuffle=shuffle)


def token_spans_to_char_offsets(tokens, spans):
    """Convert token index spans back into char spans over a joined text."""
    char_spans = []
    text = " ".join(tokens)
    current_pos = 0
    token_offsets = []

    for token in tokens:
        start = text.find(token, current_pos)
        end = start + len(token)
        token_offsets.append((start, end))
        current_pos = end + 1

    for start_idx, end_idx, label in spans:
        if start_idx < len(token_offsets) and end_idx < len(token_offsets):
            char_start = token_offsets[start_idx][0]
            char_end = token_offsets[end_idx][1]
            char_spans.append({"start": char_start, "end": char_end, "label": label})

    return text, char_spans
