import logging
import math
import random
import re
from collections import Counter

import torch
from torch.utils.data import DataLoader, WeightedRandomSampler

from base_model_training.io_utils import load_jsonl

LOGGER = logging.getLogger(__name__)


def tokenize_with_spans(text, strategy="whitespace"):
    """Split text into tokens and return (tokens, char spans)."""
    if strategy == "regex":
        matches = list(re.finditer(r"\w+|[^\w\s]", text, flags=re.UNICODE))
        return [match.group(0) for match in matches], [match.span() for match in matches]

    if strategy != "whitespace":
        raise ValueError(f"Unsupported tokenization strategy: {strategy}")

    tokens = []
    token_spans = []
    start = 0
    while start < len(text):
        while start < len(text) and text[start].isspace():
            start += 1
        if start >= len(text):
            break
        end = start
        while end < len(text) and not text[end].isspace():
            end += 1
        token = text[start:end]
        tokens.append(token)
        token_spans.append((start, end))
        start = end
    return tokens, token_spans


def process_sample(sample, tokenization_strategy="whitespace"):
    """Map char spans to token spans for a single example."""
    text = sample["text"]
    spans = sample.get("spans", [])
    tokens, token_spans = tokenize_with_spans(text, strategy=tokenization_strategy)

    ner = []
    for span in spans:
        start_char = span["start"]
        end_char = span["end"]
        label = span["label"]
        start_token = None
        end_token = None

        for i, (t_start, t_end) in enumerate(token_spans):
            if t_start >= start_char and t_end <= end_char:
                if start_token is None:
                    start_token = i
                end_token = i
            elif t_start < end_char and t_end > start_char:
                if start_token is None:
                    start_token = i
                end_token = i

        if start_token is not None and end_token is not None:
            ner.append([start_token, end_token, label])

    sample_id = sample.get("sample_id")
    return {
        "tokenized_text": tokens,
        "ner": ner,
        "sample_id": sample_id,
        "_tokenization_strategy": tokenization_strategy,
    }


def load_dataset(path, tokenization_strategy="whitespace"):
    """Load JSONL and preprocess into tokenized samples."""
    dataset = []
    assigned_sample_ids = 0
    seen_sample_ids = []
    for index, sample in enumerate(load_jsonl(path)):
        enriched = dict(sample)
        if enriched.get("sample_id") is None:
            enriched["sample_id"] = f"sample_{index}"
            assigned_sample_ids += 1
        else:
            seen_sample_ids.append(str(enriched["sample_id"]))
        dataset.append(process_sample(enriched, tokenization_strategy=tokenization_strategy))

    if assigned_sample_ids:
        LOGGER.info(
            "Assigned autogenerated sample_id values to %s input records that did not provide one.",
            assigned_sample_ids,
        )

    duplicate_counts = Counter(seen_sample_ids)
    duplicate_ids = sorted(sample_id for sample_id, count in duplicate_counts.items() if count > 1)
    if duplicate_ids:
        preview = ", ".join(duplicate_ids[:5])
        if len(duplicate_ids) > 5:
            preview += ", ..."
        LOGGER.warning(
            "Found %s duplicated sample_id values in the input dataset. "
            "Nested CV will treat records sharing a sample_id as the same group. "
            "Examples: %s",
            len(duplicate_ids),
            preview,
        )

    return dataset


def _special_tokens_to_add(tokenizer):
    """Return the number of special tokens the encoder inserts per example."""
    if tokenizer is None or not hasattr(tokenizer, "num_special_tokens_to_add"):
        return 0
    try:
        return int(tokenizer.num_special_tokens_to_add(pair=False))
    except TypeError:
        return int(tokenizer.num_special_tokens_to_add())


def _wordpiece_lengths(words, tokenizer):
    """Estimate encoder wordpiece lengths for whitespace-tokenized words."""
    if tokenizer is None:
        return [1] * len(words)

    try:
        encoded = tokenizer(
            words,
            is_split_into_words=True,
            add_special_tokens=False,
            truncation=False,
            return_attention_mask=False,
        )
        word_ids = encoded.word_ids()
        if word_ids is not None:
            lengths = [0] * len(words)
            for word_id in word_ids:
                if word_id is not None:
                    lengths[word_id] += 1
            return [length if length > 0 else 1 for length in lengths]
    except Exception:
        pass

    lengths = []
    for word in words:
        try:
            pieces = tokenizer.tokenize(word)
        except Exception:
            pieces = None
        lengths.append(len(pieces) if pieces else 1)
    return lengths


def _find_chunk_end(wordpiece_lengths, start_idx, budget, max_words=None):
    """Return the exclusive end index of the largest chunk that fits the budget."""
    used = 0
    end_idx = start_idx
    while end_idx < len(wordpiece_lengths):
        if max_words is not None and (end_idx - start_idx) >= max_words:
            break
        next_len = max(1, wordpiece_lengths[end_idx])
        if used and used + next_len > budget:
            break
        if not used and next_len > budget:
            return min(end_idx + 1, start_idx + max_words) if max_words is not None else end_idx + 1
        used += next_len
        end_idx += 1
    return end_idx


def split_long_sentences(dataset, max_length=384, overlap=50, tokenizer=None, keep_empty_chunks=False):
    """Split long tokenized sequences using encoder-aware chunk sizes."""
    split_data = []
    budget = max(1, max_length - _special_tokens_to_add(tokenizer))
    max_words = max(1, max_length)
    truncated_single_words = 0

    for sample in dataset:
        words = sample.get("tokenized_text", [])
        ner_annotations = sample.get("ner", [])

        if not words or not isinstance(ner_annotations, list):
            continue

        wordpiece_lengths = _wordpiece_lengths(words, tokenizer)
        total_wordpieces = sum(wordpiece_lengths)
        if total_wordpieces > budget:
            start_idx = 0
            while start_idx < len(words):
                end_idx = _find_chunk_end(wordpiece_lengths, start_idx, budget, max_words=max_words)
                if end_idx <= start_idx:
                    end_idx = start_idx + 1

                current_words = words[start_idx:end_idx]
                if max(wordpiece_lengths[start_idx:end_idx]) > budget:
                    truncated_single_words += 1

                new_ner = []
                for start, end, label in ner_annotations:
                    if max(start, start_idx) <= min(end, end_idx - 1):
                        adjusted_start = max(0, start - start_idx)
                        adjusted_end = min(len(current_words) - 1, end - start_idx)
                        if adjusted_start <= adjusted_end:
                            new_ner.append([adjusted_start, adjusted_end, label])

                split_sample = {
                    "tokenized_text": current_words,
                    "ner": new_ner,
                    "sample_id": sample.get("sample_id"),
                }
                if split_sample["ner"] or keep_empty_chunks:
                    split_data.append(split_sample)

                if end_idx >= len(words):
                    break

                next_start_idx = max(start_idx + 1, end_idx - overlap)
                start_idx = next_start_idx
        else:
            if ner_annotations:
                split_data.append(
                    {
                        "tokenized_text": words,
                        "ner": ner_annotations,
                        "sample_id": sample.get("sample_id"),
                    }
                )
            elif keep_empty_chunks:
                split_data.append(
                    {
                        "tokenized_text": words,
                        "ner": [],
                        "sample_id": sample.get("sample_id"),
                    }
                )

    if truncated_single_words:
        LOGGER.warning(
            "%s chunks contain at least one word whose encoder tokenization exceeds the chunk budget of %s. "
            "Those words may still be truncated by GLiNER.",
            truncated_single_words,
            budget,
        )

    if keep_empty_chunks:
        return [ex for ex in split_data if "ner" in ex and isinstance(ex["ner"], list)]
    return [ex for ex in split_data if "ner" in ex and isinstance(ex["ner"], list) and ex["ner"]]


def create_dataloader(dataset, batch_size, collator, shuffle=True):
    """Build a torch DataLoader with the GLiNER collator."""
    return DataLoader(dataset, batch_size=batch_size, collate_fn=collator, shuffle=shuffle)


def _compute_sampling_weights(dataset):
    label_counts = Counter()
    for sample in dataset:
        label_counts.update(label for _start, _end, label in sample.get("ner", []))

    weights = []
    for sample in dataset:
        labels = {label for _start, _end, label in sample.get("ner", [])}
        if labels:
            weight = sum(1.0 / label_counts[label] for label in labels if label_counts[label] > 0)
        else:
            weight = 1.0
        weights.append(max(weight, 1e-8))
    return weights


def _build_non_empty_batches(dataset, batch_size, rng):
    positive_indices = [index for index, sample in enumerate(dataset) if sample.get("ner")]
    negative_indices = [index for index, sample in enumerate(dataset) if not sample.get("ner")]

    if not positive_indices:
        raise ValueError("Training dataset cannot contain only empty-entity chunks.")

    rng.shuffle(positive_indices)
    rng.shuffle(negative_indices)

    max_negatives = len(positive_indices) * max(0, batch_size - 1)
    dropped_negatives = max(0, len(negative_indices) - max_negatives)
    if dropped_negatives:
        LOGGER.warning(
            "Sampling %s/%s empty chunks this epoch so every batch keeps at least one positive example.",
            max_negatives,
            len(negative_indices),
        )
        negative_indices = negative_indices[:max_negatives]

    total = len(positive_indices) + len(negative_indices)
    num_batches = max(1, math.ceil(total / batch_size))
    if num_batches > len(positive_indices):
        num_batches = len(positive_indices)

    batches = [[positive_indices.pop()] for _ in range(num_batches)]
    remaining = positive_indices + negative_indices
    rng.shuffle(remaining)

    batch_cursor = 0
    for index in remaining:
        attempts = 0
        while attempts < len(batches) and len(batches[batch_cursor]) >= batch_size:
            batch_cursor = (batch_cursor + 1) % len(batches)
            attempts += 1
        if attempts >= len(batches):
            break
        batches[batch_cursor].append(index)
        batch_cursor = (batch_cursor + 1) % len(batches)

    return batches


class _NonEmptyBatchSampler:
    def __init__(self, dataset, batch_size, seed=42):
        self.dataset = dataset
        self.batch_size = batch_size
        self.seed = seed
        self._epoch = 0

    def __iter__(self):
        rng = random.Random(self.seed + self._epoch)
        self._epoch += 1
        yield from _build_non_empty_batches(self.dataset, self.batch_size, rng)

    def __len__(self):
        positives = sum(1 for sample in self.dataset if sample.get("ner"))
        negatives = sum(1 for sample in self.dataset if not sample.get("ner"))
        usable_negatives = min(negatives, positives * max(0, self.batch_size - 1))
        total = positives + usable_negatives
        return max(1, math.ceil(total / self.batch_size))


def create_training_dataloader(dataset, batch_size, collator, sampling="random"):
    """Build the training DataLoader with configurable example sampling."""
    has_empty_chunks = any(not sample.get("ner") for sample in dataset)
    if has_empty_chunks:
        if sampling == "weighted":
            LOGGER.warning(
                "Weighted sampling is not compatible with empty-only GLiNER batches; "
                "falling back to non-empty-safe batching for this epoch."
            )
        return DataLoader(
            dataset,
            collate_fn=collator,
            batch_sampler=_NonEmptyBatchSampler(dataset, batch_size=batch_size),
        )

    if sampling == "random":
        return DataLoader(dataset, batch_size=batch_size, collate_fn=collator, shuffle=True)

    if sampling == "weighted":
        weights = _compute_sampling_weights(dataset)
        sampler = WeightedRandomSampler(
            weights=torch.tensor(weights, dtype=torch.double),
            num_samples=len(dataset),
            replacement=True,
        )
        return DataLoader(dataset, batch_size=batch_size, collate_fn=collator, sampler=sampler)

    raise ValueError(f"Unsupported train sampling mode: {sampling}")


def token_spans_to_char_offsets(tokens, spans):
    """Convert token index spans back into char spans over a joined text."""
    char_spans = []
    text = " ".join(tokens)
    current_pos = 0
    token_offsets = []

    for token in tokens:
        start = text.find(token, current_pos)
        end = start + len(token)
        token_offsets.append((start, end))
        current_pos = end + 1

    for start_idx, end_idx, label in spans:
        if start_idx < len(token_offsets) and end_idx < len(token_offsets):
            char_start = token_offsets[start_idx][0]
            char_end = token_offsets[end_idx][1]
            char_spans.append({"start": char_start, "end": char_end, "label": label})

    return text, char_spans
